server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mutualfunds
spring.datasource.username=postgres
spring.datasource.password=root

# \u2705 VERY IMPORTANT FIX
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true